# Book settings
title: Pythonomics
author: Max Ghenis


launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/MaxGhenis/pythonomics
  branch: master
  path_to_book: book

html:
  use_edit_page_button  : true
  use_repository_button : true
  use_issues_button     : true
